apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  ports:
    protocol: TCP
    port: {{ .Values.test_app.port }}
    targetPort: {{ .Values.test_app.TargetPort }}
  selector:
    app: {{ .Values.app }}
  type: ClusterIP
