apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.test-app.port }}
      targetPort: {{ .Values.test-app.nodePort }}
  selector:
    app: {{ .Values.app }}
  type: ClusterIP